# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD license
# that can be found in the LICENSE file.

# https://coreos.com/etcd/docs/latest/op-guide/container.html#docker
# https://coreos.com/etcd/docs/latest/v2/api.html

version: '3'

services:
  etcd-node1:
    image: "chai2010/etcd"
    volumes:
    - ./etcd-conf:/etcd-conf
    - ./etcd-node1-data:/etcd-data
    ports:
    - "2379:2379" # only for debug
    command: [
      "etcd", "-config-file=/etcd-conf/etcd-node1.yml"
    ]

  etcd-node2:
    image: "chai2010/etcd"
    volumes:
    - ./etcd-conf:/etcd-conf
    - ./etcd-node2-data:/etcd-data
    ports:
    - "3379:2379" # only for debug
    command: [
      "etcd", "-config-file=/etcd-conf/etcd-node2.yml"
    ]

  etcd-node3:
    image: "chai2010/etcd"
    volumes:
    - ./etcd-conf:/etcd-conf
    - ./etcd-node3-data:/etcd-data
    ports:
    - "4379:2379" # only for debug
    command: [
      "etcd", "-config-file=/etcd-conf/etcd-node3.yml"
    ]

