# Copyright 2017 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD license
# that can be found in the LICENSE file.

[template]
src = "myapp.json.tmpl"
dest = "/etc/myapp/myapp.json"

keys = [
    "/myapp/database/url",
    "/myapp/database/user",
]

check_cmd = ""
reload_cmd = "echo reload chai"
